name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  main:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        go: [ '1.15' ]
    name: Go ${{ matrix.go }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      id: go
      with:
        go-version: ${{ matrix.go }}

    - name: Verify modules
      run: go mod verify

    - name: Verify format
      run: |
        make fmt
        git diff --exit-code

    - name: Test
      run: make test

    - name: Build
      run: make
